services:
    killsoft_tiger.menu_builder:
        class: Killsoft\TigerBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: killsoft_tiger.menu_builder
        factory_method: mainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
