killsoft_tiger:
    resource: "@KillsoftTigerBundle/Resources/config/routing.yml"
    prefix:   /

killsoft_blog:
    resource: "@KillsoftBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
